/*
 * Bloodhound Hypercall Interface
 */

#ifndef BLOODHOUND_HYPERCALL_H
#define BLOODHOUND_HYPERCALL_H

#define BLOODHOUND_HYPERCALL_BASE    0xBD000000

#define BLOODHOUND_GET_RANDOM        (BLOODHOUND_HYPERCALL_BASE + 0)
#define BLOODHOUND_GET_TIME          (BLOODHOUND_HYPERCALL_BASE + 1)
#define BLOODHOUND_SNAPSHOT_CREATE   (BLOODHOUND_HYPERCALL_BASE + 2)
#define BLOODHOUND_SNAPSHOT_RESTORE  (BLOODHOUND_HYPERCALL_BASE + 3)
#define BLOODHOUND_LOG_EVENT         (BLOODHOUND_HYPERCALL_BASE + 4)
#define BLOODHOUND_SET_SEED          (BLOODHOUND_HYPERCALL_BASE + 5)

#endif /* BLOODHOUND_HYPERCALL_H */
